// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  tournamentId: __t.u32(),
  fighter1Id: __t.u32(),
  action: __t.string(),
  fighter2Id: __t.u32(),
  roundsDuration: __t.u32(),
  side: __t.string(),
  amount: __t.f64(),
};
