// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  tournamentId: __t.u32().name("tournament_id"),
  creatorId: __t.identity().name("creator_id"),
  fighter1Id: __t.u32().name("fighter_1_id"),
  action: __t.string(),
  fighter2Id: __t.u32().name("fighter_2_id"),
  roundsDuration: __t.u32().name("rounds_duration"),
  startHour: __t.u32().name("start_hour"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
