// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  name: __t.string(),
  lore: __t.string(),
  archetype: __t.string(),
  strength: __t.u8(),
  speed: __t.u8(),
  intelligence: __t.u8(),
  luck: __t.u8(),
  charisma: __t.u8(),
  points: __t.u32(),
  totalPointsEarned: __t.u32().name("total_points_earned"),
  wins: __t.u32(),
  tournamentsPlayed: __t.u32().name("tournaments_played"),
  isUserCreated: __t.bool().name("is_user_created"),
  ownerIdentity: __t.option(__t.identity()).name("owner_identity"),
  avatarUrl: __t.string().name("avatar_url"),
});
