// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdminCreateTournamentReducer from "./admin_create_tournament_reducer";
import AdvanceHourReducer from "./advance_hour_reducer";
import CreateEventBetSlipReducer from "./create_event_bet_slip_reducer";
import ClaimAdminReducer from "./claim_admin_reducer";
import CreateFighterReducer from "./create_fighter_reducer";
import CreateTournamentReducer from "./create_tournament_reducer";
import HostTournamentReducer from "./host_tournament_reducer";
import JoinEventBetSlipReducer from "./join_event_bet_slip_reducer";
import MarkAllNotificationsReadReducer from "./mark_all_notifications_read_reducer";
import MarkNotificationReadReducer from "./mark_notification_read_reducer";
import PlaceBetReducer from "./place_bet_reducer";
import PlaceBidReducer from "./place_bid_reducer";
import RegisterForTournamentReducer from "./register_for_tournament_reducer";
import RegisterUserReducer from "./register_user_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import ResetAvatarsReducer from "./reset_avatars_reducer";
import ResetFighterStatsReducer from "./reset_fighter_stats_reducer";
import RespondToFriendRequestReducer from "./respond_to_friend_request_reducer";
import SendFriendRequestReducer from "./send_friend_request_reducer";
import SetAdminReducer from "./set_admin_reducer";
import SponsorFighterReducer from "./sponsor_fighter_reducer";
import StartTournamentReducer from "./start_tournament_reducer";
import UnregisterFromTournamentReducer from "./unregister_from_tournament_reducer";
import UpdateAccountReducer from "./update_account_reducer";
import UpdateProfileReducer from "./update_profile_reducer";
import VerifyLoginReducer from "./verify_login_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ArenaTileRow from "./arena_tile_table";
import AuctionBidRow from "./auction_bid_table";
import BetRow from "./bet_table";
import ContractRow from "./contract_table";
import EventBetPositionRow from "./event_bet_position_table";
import EventBetSlipRow from "./event_bet_slip_table";
import FighterTemplateRow from "./fighter_template_table";
import FriendshipRow from "./friendship_table";
import LiveEventRow from "./live_event_table";
import NotificationRow from "./notification_table";
import SponsorDropRow from "./sponsor_drop_table";
import TournamentRow from "./tournament_table";
import TournamentFighterRow from "./tournament_fighter_table";
import TournamentRegistrationRow from "./tournament_registration_table";
import UserRow from "./user_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  arenaTile: __table({
    name: 'arenaTile',
    indexes: [
      { accessor: 'id', name: 'arenaTile_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'arenaTile_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'arenaTile_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ArenaTileRow),
  auctionBid: __table({
    name: 'auctionBid',
    indexes: [
      { accessor: 'fighterId', name: 'auctionBid_fighter_id_idx_btree', algorithm: 'btree', columns: [
        'fighterId',
      ] },
      { accessor: 'id', name: 'auctionBid_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'auctionBid_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuctionBidRow),
  bet: __table({
    name: 'bet',
    indexes: [
      { accessor: 'id', name: 'bet_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'bet_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
      { accessor: 'userId', name: 'bet_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'bet_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BetRow),
  contract: __table({
    name: 'contract',
    indexes: [
      { accessor: 'id', name: 'contract_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'userId', name: 'contract_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'contract_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContractRow),
  eventBetPosition: __table({
    name: 'eventBetPosition',
    indexes: [
      { accessor: 'id', name: 'eventBetPosition_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'slipId', name: 'eventBetPosition_slip_id_idx_btree', algorithm: 'btree', columns: [
        'slipId',
      ] },
    ],
    constraints: [
      { name: 'eventBetPosition_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventBetPositionRow),
  eventBetSlip: __table({
    name: 'eventBetSlip',
    indexes: [
      { accessor: 'id', name: 'eventBetSlip_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'eventBetSlip_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'eventBetSlip_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EventBetSlipRow),
  fighterTemplate: __table({
    name: 'fighterTemplate',
    indexes: [
      { accessor: 'id', name: 'fighterTemplate_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'fighterTemplate_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FighterTemplateRow),
  friendship: __table({
    name: 'friendship',
    indexes: [
      { accessor: 'addresseeId', name: 'friendship_addressee_id_idx_btree', algorithm: 'btree', columns: [
        'addresseeId',
      ] },
      { accessor: 'id', name: 'friendship_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_pair', name: 'friendship_requester_id_addressee_id_idx_btree', algorithm: 'btree', columns: [
        'requesterId',
        'addresseeId',
      ] },
      { accessor: 'requesterId', name: 'friendship_requester_id_idx_btree', algorithm: 'btree', columns: [
        'requesterId',
      ] },
    ],
    constraints: [
      { name: 'friendship_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, FriendshipRow),
  liveEvent: __table({
    name: 'liveEvent',
    indexes: [
      { accessor: 'id', name: 'liveEvent_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'liveEvent_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'liveEvent_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LiveEventRow),
  notification: __table({
    name: 'notification',
    indexes: [
      { accessor: 'id', name: 'notification_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'by_recipient', name: 'notification_recipient_id_created_at_idx_btree', algorithm: 'btree', columns: [
        'recipientId',
        'createdAt',
      ] },
      { accessor: 'recipientId', name: 'notification_recipient_id_idx_btree', algorithm: 'btree', columns: [
        'recipientId',
      ] },
    ],
    constraints: [
      { name: 'notification_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NotificationRow),
  sponsorDrop: __table({
    name: 'sponsorDrop',
    indexes: [
      { accessor: 'id', name: 'sponsorDrop_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'sponsorDrop_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'sponsorDrop_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SponsorDropRow),
  tournament: __table({
    name: 'tournament',
    indexes: [
      { accessor: 'id', name: 'tournament_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tournament_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TournamentRow),
  tournamentFighter: __table({
    name: 'tournamentFighter',
    indexes: [
      { accessor: 'fighterId', name: 'tournamentFighter_fighter_id_idx_btree', algorithm: 'btree', columns: [
        'fighterId',
      ] },
      { accessor: 'id', name: 'tournamentFighter_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'tournamentFighter_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
    ],
    constraints: [
      { name: 'tournamentFighter_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TournamentFighterRow),
  tournamentRegistration: __table({
    name: 'tournamentRegistration',
    indexes: [
      { accessor: 'id', name: 'tournamentRegistration_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'tournamentId', name: 'tournamentRegistration_tournament_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
      ] },
      { accessor: 'by_tournament', name: 'tournamentRegistration_tournament_id_user_id_idx_btree', algorithm: 'btree', columns: [
        'tournamentId',
        'userId',
      ] },
      { accessor: 'userId', name: 'tournamentRegistration_user_id_idx_btree', algorithm: 'btree', columns: [
        'userId',
      ] },
    ],
    constraints: [
      { name: 'tournamentRegistration_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TournamentRegistrationRow),
  user: __table({
    name: 'user',
    indexes: [
      { accessor: 'identity', name: 'user_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("adminCreateTournament", AdminCreateTournamentReducer),
  __reducerSchema("advanceHour", AdvanceHourReducer),
  __reducerSchema("createEventBetSlip", CreateEventBetSlipReducer),
  __reducerSchema("createFighter", CreateFighterReducer),
  __reducerSchema("createTournament", CreateTournamentReducer),
  __reducerSchema("hostTournament", HostTournamentReducer),
  __reducerSchema("joinEventBetSlip", JoinEventBetSlipReducer),
  __reducerSchema("claimAdmin", ClaimAdminReducer),
  __reducerSchema("markAllNotificationsRead", MarkAllNotificationsReadReducer),
  __reducerSchema("markNotificationRead", MarkNotificationReadReducer),
  __reducerSchema("placeBet", PlaceBetReducer),
  __reducerSchema("placeBid", PlaceBidReducer),
  __reducerSchema("registerForTournament", RegisterForTournamentReducer),
  __reducerSchema("registerUser", RegisterUserReducer),
  __reducerSchema("removeFriend", RemoveFriendReducer),
  __reducerSchema("resetAvatars", ResetAvatarsReducer),
  __reducerSchema("resetFighterStats", ResetFighterStatsReducer),
  __reducerSchema("respondToFriendRequest", RespondToFriendRequestReducer),
  __reducerSchema("sendFriendRequest", SendFriendRequestReducer),
  __reducerSchema("setAdmin", SetAdminReducer),
  __reducerSchema("sponsorFighter", SponsorFighterReducer),
  __reducerSchema("startTournament", StartTournamentReducer),
  __reducerSchema("unregisterFromTournament", UnregisterFromTournamentReducer),
  __reducerSchema("updateAccount", UpdateAccountReducer),
  __reducerSchema("updateProfile", UpdateProfileReducer),
  __reducerSchema("verifyLogin", VerifyLoginReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

