// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  recipientId: __t.identity().name("recipient_id"),
  kind: __t.string(),
  title: __t.string(),
  body: __t.string(),
  relatedId: __t.option(__t.u32()).name("related_id"),
  read: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
