// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArenaTile = __t.object("ArenaTile", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  x: __t.u8(),
  y: __t.u8(),
  tileType: __t.string(),
  hasResource: __t.bool(),
  resourceType: __t.option(__t.string()),
});
export type ArenaTile = __Infer<typeof ArenaTile>;

export const AuctionBid = __t.object("AuctionBid", {
  id: __t.u32(),
  fighterId: __t.u32(),
  bidderId: __t.identity(),
  amount: __t.f64(),
  placedAt: __t.timestamp(),
});
export type AuctionBid = __Infer<typeof AuctionBid>;

export const Bet = __t.object("Bet", {
  id: __t.u32(),
  userId: __t.identity(),
  tournamentId: __t.u32(),
  fighterId: __t.u32(),
  betType: __t.string(),
  amount: __t.f64(),
  odds: __t.f64(),
  status: __t.string(),
  placedAt: __t.timestamp(),
});
export type Bet = __Infer<typeof Bet>;

export const Contract = __t.object("Contract", {
  id: __t.u32(),
  userId: __t.identity(),
  fighterId: __t.u32(),
  tournamentsRemaining: __t.u8(),
  totalEarned: __t.f64(),
  createdAt: __t.timestamp(),
});
export type Contract = __Infer<typeof Contract>;

export const FighterTemplate = __t.object("FighterTemplate", {
  id: __t.u32(),
  name: __t.string(),
  lore: __t.string(),
  archetype: __t.string(),
  strength: __t.u8(),
  speed: __t.u8(),
  intelligence: __t.u8(),
  luck: __t.u8(),
  charisma: __t.u8(),
  points: __t.u32(),
  totalPointsEarned: __t.u32(),
  wins: __t.u32(),
  tournamentsPlayed: __t.u32(),
  isUserCreated: __t.bool(),
  ownerIdentity: __t.option(__t.identity()),
  avatarUrl: __t.string(),
});
export type FighterTemplate = __Infer<typeof FighterTemplate>;

export const Friendship = __t.object("Friendship", {
  id: __t.u32(),
  requesterId: __t.identity(),
  addresseeId: __t.identity(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Friendship = __Infer<typeof Friendship>;

export const LiveEvent = __t.object("LiveEvent", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  hour: __t.u32(),
  eventType: __t.string(),
  description: __t.string(),
  involvedIds: __t.string(),
  x: __t.option(__t.u8()),
  y: __t.option(__t.u8()),
  timestamp: __t.timestamp(),
});
export type LiveEvent = __Infer<typeof LiveEvent>;

export const Notification = __t.object("Notification", {
  id: __t.u32(),
  recipientId: __t.identity(),
  kind: __t.string(),
  title: __t.string(),
  body: __t.string(),
  relatedId: __t.option(__t.u32()),
  read: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Notification = __Infer<typeof Notification>;

export const SponsorDrop = __t.object("SponsorDrop", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  userId: __t.identity(),
  fighterId: __t.u32(),
  itemType: __t.string(),
  cost: __t.f64(),
  status: __t.string(),
  dropX: __t.option(__t.u8()),
  dropY: __t.option(__t.u8()),
  queuedHour: __t.u32(),
  deliveryHour: __t.u32(),
});
export type SponsorDrop = __Infer<typeof SponsorDrop>;

export const Tournament = __t.object("Tournament", {
  id: __t.u32(),
  name: __t.string(),
  arenaType: __t.string(),
  status: __t.string(),
  currentHour: __t.u32(),
  gridWidth: __t.u8(),
  gridHeight: __t.u8(),
  prizePool: __t.f64(),
  hostIdentity: __t.option(__t.identity()),
  createdAt: __t.timestamp(),
});
export type Tournament = __Infer<typeof Tournament>;

export const TournamentFighter = __t.object("TournamentFighter", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  fighterId: __t.u32(),
  isAlive: __t.bool(),
  x: __t.u8(),
  y: __t.u8(),
  hunger: __t.u8(),
  thirst: __t.u8(),
  fatigue: __t.u8(),
  injury: __t.u8(),
  morale: __t.u8(),
  condition: __t.string(),
  inventory: __t.string(),
  alliances: __t.string(),
  kills: __t.u8(),
  eliminatedHour: __t.option(__t.u32()),
});
export type TournamentFighter = __Infer<typeof TournamentFighter>;

export const TournamentRegistration = __t.object("TournamentRegistration", {
  id: __t.u32(),
  tournamentId: __t.u32(),
  userId: __t.identity(),
  role: __t.string(),
  registeredAt: __t.timestamp(),
});
export type TournamentRegistration = __Infer<typeof TournamentRegistration>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  email: __t.string(),
  passwordHash: __t.string(),
  balance: __t.f64(),
  tournamentsHosted: __t.u32(),
  fightersOwned: __t.u32(),
  createdAt: __t.timestamp(),
  bio: __t.string(),
  avatarEmoji: __t.string(),
  favoriteArchetype: __t.string(),
  isAdmin: __t.bool(),
});
export type User = __Infer<typeof User>;

