// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  email: __t.string(),
  passwordHash: __t.string().name("password_hash"),
  balance: __t.f64(),
  tournamentsHosted: __t.u32().name("tournaments_hosted"),
  fightersOwned: __t.u32().name("fighters_owned"),
  createdAt: __t.timestamp().name("created_at"),
  bio: __t.string(),
  avatarEmoji: __t.string().name("avatar_emoji"),
  favoriteArchetype: __t.string().name("favorite_archetype"),
  isAdmin: __t.bool().name("is_admin"),
});
